!!submodule.data.MainConfig
charts:
  Bacteria_Genus:
    data:
      Bacteria:
      - 1
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count OtherBacteria
      xAxisTitle: null
      xCategories:
      - Bacillus
      yAxisTitle: null
      yCategories:
      - 100.0
  Viruses_Genus:
    data:
      Viruses:
      - 3
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count OtherViruses
      xAxisTitle: null
      xCategories:
      - Alphapapillomavirus
      yAxisTitle: null
      yCategories:
      - 100.0
  Projects:
    data:
      project:
      - 11
      - 1
      - 1
    settings:
      subtitle: null
      tabTitle: Projects
      title: Project Counts with Measured Samples
      xAxisTitle: null
      xCategories:
      - Q_MS_RUN
      - Q_MICROARRAY_RUN
      - Multi_omics
      yAxisTitle: null
      yCategories:
      - 7.7
      - 7.7
      - 84.6
  Available_Workflows_MA_RNA:
    data:
      stargazers_count:
      - 1.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows MA_RNA
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/qbic-wf-microarrayQC
      yAxisTitle: null
      yCategories:
      - Microarray QC workflow mainly using the R package oligo
  Project_Multi_omics:
    data:
      multiomics:
      - 1
    settings:
      subtitle: null
      tabTitle: Projects
      title: Multiomics count
      xAxisTitle: null
      xCategories:
      - Microarray + NGS
      yAxisTitle: null
      yCategories: null
  SuperKingdom:
    data:
      SuperKingdom:
      - 8
      - 1
      - 6
      - 313
      - 3
      - 112
      - 9
      - 3
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count by Domain
      xAxisTitle: null
      xCategories:
      - unclassified sequences
      - Other Bacteria
      - Amycolatopsis japonica
      - Other Eukaryota
      - Viruses
      - Homo sapiens
      - Caulobacter crescentus CB15
      - Other
      yAxisTitle: null
      yCategories:
      - 1.8
      - 0.2
      - 1.3
      - 68.8
      - 0.7
      - 24.6
      - 2.0
      - 0.7
  Viruses_Species:
    data:
      Viruses:
      - 3
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - Human papillomavirus type 16
      yAxisTitle: null
      yCategories:
      - 100.0
  Species_Genus:
    data:
      Species_Genus:
      - Salpiglossis
      - Vinca
      - Amphilophus
      - Brassica
      - Lavandula
      - Helichrysum
      - Sanicula
      - Nicotiana
      - Asparagus
      - Arabidopsis
      - Canis
      - Achillea
      - Salvia
      - Schizosaccharomyces
      - Melissa
      - Macrostomum
      - Descurainia
      - Astrantia
      - Foeniculum
      - Isatis
      - Amycolatopsis
      - Erysimum
      - Allium
      - Homo
      - Bupleurum
      - Caulobacter
      - Bos
      - Alphapapillomavirus
      - Ajuga
      - Caenorhabditis
      - Calendula
      - Matthiola
      - Apis
      - Phlomis
      - Saccharomyces
      - Physalis
      - Iberis
      - Mus
      - Bacillus
      - Petunia
      - Nicotiana
      - Echinacea
      - Tagetes
      - Danio
      - Bupleurum
      - Nicotiana
      - Eupatorium
      - Athamanta
      - Teucrium
      - Leonurus
      - Levisticum
      - Ambrosia
      - null
      - Bunias
      - Mentha
      - Capra
      - Erysimum
      - Seseli
      - Stachys
      - Petroselinum
      - Ocimum
      - Carduus
      - Capsicum
      - Centaurea
      - Physalis
      - Carum
      - Aurinia
      - Artemisia
      - Brassica
      - Artemisia
      - null
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - Salpiglossis sinuata
      - Vinca major
      - Amphilophus (nicaraguan)
      - Brassica oleracea var. oleracea
      - Lavandula canariensis
      - Helichrysum arenarium
      - Sanicula odorata
      - Nicotiana longiflora
      - Asparagus officinalis
      - Arabidopsis thaliana
      - Canis lupus familiaris
      - Achillea millefolium
      - Salvia officinalis
      - Schizosaccharomyces pombe
      - Melissa officinalis
      - Macrostomum lignano
      - Descurainia millefolia
      - Astrantia major
      - Foeniculum vulgare
      - Isatis tinctoria
      - Amycolatopsis japonica
      - Erysimum scoparium
      - Allium ampeloprasum
      - Homo sapiens
      - Bupleurum falcatum
      - Caulobacter crescentus CB15
      - Bos taurus
      - Human papillomavirus type 16
      - Ajuga reptans
      - Caenorhabditis elegans
      - Calendula officinalis
      - Matthiola incana
      - Apis mellifera mellifera
      - Phlomis viscosa
      - Saccharomyces cerevisiae
      - Physalis alkekengi
      - Iberis sempervirens
      - Mus musculus
      - Bacillus cereus strain ATCC 10987
      - Petunia axillaris
      - Nicotiana rustica
      - Echinacea purpurea
      - Tagetes erecta
      - Danio rerio
      - Bupleurum canescens var. handiense
      - Nicotiana tabacum
      - Eupatorium cannabinum
      - Athamanta cretensis
      - Teucrium chamaedrys
      - Leonurus cardiaca
      - Levisticum officinale
      - Ambrosia artemisiifolia
      - Unidentified
      - Bunias orientalis
      - Mentha x piperita
      - Capra hircus
      - Erysimum cheiri
      - Seseli libanotis
      - Stachys byzantina
      - Petroselinum crispum
      - Ocimum basilicum
      - Carduus defloratus
      - Capsicum frutescens
      - Centaurea montana
      - Physalis peruviana
      - Carum carvi
      - Aurinia saxatilis
      - Artemisia absinthium
      - Brassica napus
      - Artemisia abrotanum
      - Other
      yAxisTitle: null
      yCategories: null
  Available_Workflows_NGS_RNA:
    data:
      stargazers_count:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows NGS_RNA
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/rnamapping
      - https://api.github.com/repos/qbicsoftware/merge-NGSdata-workflow
      - https://api.github.com/repos/qbicsoftware/rnacount
      - https://api.github.com/repos/qbicsoftware/differentialexpression-analysis-workflow
      - https://api.github.com/repos/qbicsoftware/rnaseq
      - https://api.github.com/repos/qbicsoftware/ngsqc
      - https://api.github.com/repos/qbicsoftware/optitype-workflow
      - https://api.github.com/repos/qbicsoftware/epaa-workflow
      - https://api.github.com/repos/qbicsoftware/qbic-workflow-epitopeprediction
      yAxisTitle: null
      yCategories:
      - ''
      - Quality Control on fastq files
      - ''
      - RNAseq workflow
      - ''
      - ''
      - Workflow scripts for merging NGS raw data (lanes)
      - Differential expression analysis using DESeq2
      - Epitope prediction workflow based on FRED.
  Available_Workflows_NGS_DNA:
    data:
      stargazers_count:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows NGS_DNA
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/variantcalling
      - https://api.github.com/repos/qbicsoftware/mapping
      - https://api.github.com/repos/qbicsoftware/merge-NGSdata-workflow
      - https://api.github.com/repos/qbicsoftware/qbic-workflow-indproteome
      - https://api.github.com/repos/qbicsoftware/variant-annotation-workflow
      - https://api.github.com/repos/qbicsoftware/exomseq
      - https://api.github.com/repos/qbicsoftware/ngsqc
      - https://api.github.com/repos/qbicsoftware/16Smetagenomics-taxonomic-profiling
      - https://api.github.com/repos/qbicsoftware/optitype-workflow
      - https://api.github.com/repos/qbicsoftware/somatic-variantcalling-workflow
      - https://api.github.com/repos/qbicsoftware/epaa-workflow
      - https://api.github.com/repos/qbicsoftware/qbic-workflow-epitopeprediction
      yAxisTitle: null
      yCategories:
      - ''
      - Quality Control on fastq files
      - ''
      - ''
      - Repository for variant calling pipeline using FreeBayes
      - ''
      - ''
      - Workflow scripts for merging NGS raw data (lanes)
      - Workflow scripts for somatic variant calling workflow (Strelka)
      - Workflow scripts of the variant annotation workflow
      - Epitope prediction workflow based on FRED.
      - Workflow to create personalized protein references using FRED2.
  Eukaryota_Genus:
    data:
      Eukaryota:
      - 3
      - 1
      - 3
      - 2
      - 3
      - 18
      - 4
      - 3
      - 3
      - 3
      - 3
      - 3
      - 9
      - 3
      - 5
      - 3
      - 2
      - 15
      - 51
      - 1
      - 3
      - 2
      - 22
      - 3
      - 3
      - 1
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 6
      - 5
      - 5
      - 3
      - 3
      - 3
      - 2
      - 6
      - 3
      - 16
      - 23
      - 3
      - 6
      - 3
      - 3
      - 2
      - 6
      - 3
      - 3
      - 3
      - 5
      - 3
      - 3
      - 2
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count OtherEukaryota
      xAxisTitle: null
      xCategories:
      - Foeniculum
      - Macrostomum
      - Astrantia
      - Canis
      - Aurinia
      - Saccharomyces
      - Melissa
      - Carum
      - Petunia
      - Eupatorium
      - Carduus
      - Athamanta
      - Nicotiana
      - Stachys
      - Physalis
      - Seseli
      - Apis
      - Bos
      - Mus
      - Allium
      - Lavandula
      - Amphilophus
      - Danio
      - Echinacea
      - Salvia
      - Capra
      - Centaurea
      - Ocimum
      - Helichrysum
      - Descurainia
      - Levisticum
      - Phlomis
      - Petroselinum
      - Bupleurum
      - Erysimum
      - Caenorhabditis
      - Matthiola
      - Salpiglossis
      - Mentha
      - Schizosaccharomyces
      - Ajuga
      - Bunias
      - Arabidopsis
      - Asparagus
      - Teucrium
      - Artemisia
      - Leonurus
      - Calendula
      - Ambrosia
      - Brassica
      - Isatis
      - Vinca
      - Iberis
      - Achillea
      - Sanicula
      - Tagetes
      - Capsicum
      yAxisTitle: null
      yCategories:
      - 1.0
      - 0.3
      - 1.0
      - 0.6
      - 1.0
      - 5.8
      - 1.3
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 2.9
      - 1.0
      - 1.6
      - 1.0
      - 0.6
      - 4.8
      - 16.3
      - 0.3
      - 1.0
      - 0.6
      - 7.0
      - 1.0
      - 1.0
      - 0.3
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.9
      - 1.6
      - 1.6
      - 1.0
      - 1.0
      - 1.0
      - 0.6
      - 1.9
      - 1.0
      - 5.1
      - 7.3
      - 1.0
      - 1.9
      - 1.0
      - 1.0
      - 0.6
      - 1.9
      - 1.0
      - 1.0
      - 1.0
      - 1.6
      - 1.0
      - 1.0
      - 0.6
  Available_Workflows_MS_PX:
    data:
      stargazers_count:
      - 6.0
      - 2.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows MS_PX
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/mqrun
      - https://api.github.com/repos/qbicsoftware/qcprot
      yAxisTitle: null
      yCategories:
      - Automate MaxQuant
      - Quality control for mass spec proteomics
  Available_Workflows_OTHER:
    data:
      stargazers_count:
      - 1.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows OTHER
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/qbic-workflow-nf-rnaseq
      yAxisTitle: null
      yCategories:
      - Our RNAseq workflow modularized in nextflow
  Workflow_Execution_Counts:
    data:
      Counts:
      - 8
      - 78
      - 143
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Workflow Execution Counts
      xAxisTitle: null
      xCategories:
      - MA
      - MS
      - NGS
      yAxisTitle: null
      yCategories:
      - 3.5
      - 34.1
      - 62.4
  Sample_Types:
    data:
      Samples:
      - PEPTIDES: 39
        DNA: 1
        PROTEINS: 13
      - RNA: 17
        PROTEINS: 3
      - RNA: 1
    settings:
      subtitle: null
      tabTitle: Samples
      title: Number of Already Measured Samples
      xAxisTitle: null
      xCategories:
      - Q_MS_RUN
      - Q_MICROARRAY_RUN
      - Multi-omics
      yAxisTitle: null
      yCategories: null
  Bacteria_Species:
    data:
      Bacteria:
      - 1
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - Bacillus cereus strain ATCC 10987
      yAxisTitle: null
      yCategories:
      - 100.0
  Available_Workflows_MS_LX:
    data:
      stargazers_count:
      - 0.0
      - 0.0
      - 0.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows MS_LX
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/ligandomics-QC-workflow
      - https://api.github.com/repos/qbicsoftware/ligandomics-ID-workflow-copro
      - https://api.github.com/repos/qbicsoftware/ligandomics-ID-workflow
      yAxisTitle: null
      yCategories:
      - ''
      - ''
      - Workflow scripts of the ligandomics QC workflow
  Eukaryota_Species:
    data:
      Eukaryota:
      - 3
      - 3
      - 2
      - 3
      - 3
      - 3
      - 3
      - 3
      - 23
      - 16
      - 2
      - 5
      - 3
      - 2
      - 4
      - 1
      - 3
      - 3
      - 3
      - 3
      - 2
      - 1
      - 3
      - 15
      - 6
      - 5
      - 3
      - 3
      - 2
      - 3
      - 18
      - 2
      - 3
      - 51
      - 3
      - 3
      - 3
      - 3
      - 22
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 2
      - 3
      - 3
      - 1
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 2
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - Salpiglossis sinuata
      - Vinca major
      - Amphilophus (nicaraguan)
      - Brassica oleracea var. oleracea
      - Lavandula canariensis
      - Helichrysum arenarium
      - Sanicula odorata
      - Nicotiana longiflora
      - Asparagus officinalis
      - Arabidopsis thaliana
      - Canis lupus familiaris
      - Achillea millefolium
      - Salvia officinalis
      - Schizosaccharomyces pombe
      - Melissa officinalis
      - Macrostomum lignano
      - Descurainia millefolia
      - Astrantia major
      - Foeniculum vulgare
      - Isatis tinctoria
      - Erysimum scoparium
      - Allium ampeloprasum
      - Bupleurum falcatum
      - Bos taurus
      - Ajuga reptans
      - Caenorhabditis elegans
      - Calendula officinalis
      - Matthiola incana
      - Apis mellifera mellifera
      - Phlomis viscosa
      - Saccharomyces cerevisiae
      - Physalis alkekengi
      - Iberis sempervirens
      - Mus musculus
      - Petunia axillaris
      - Nicotiana rustica
      - Echinacea purpurea
      - Tagetes erecta
      - Danio rerio
      - Bupleurum canescens var. handiense
      - Nicotiana tabacum
      - Eupatorium cannabinum
      - Athamanta cretensis
      - Teucrium chamaedrys
      - Leonurus cardiaca
      - Levisticum officinale
      - Ambrosia artemisiifolia
      - Bunias orientalis
      - Mentha x piperita
      - Capra hircus
      - Erysimum cheiri
      - Seseli libanotis
      - Stachys byzantina
      - Petroselinum crispum
      - Ocimum basilicum
      - Carduus defloratus
      - Capsicum frutescens
      - Centaurea montana
      - Physalis peruviana
      - Carum carvi
      - Aurinia saxatilis
      - Artemisia absinthium
      - Brassica napus
      - Artemisia abrotanum
      yAxisTitle: null
      yCategories:
      - 1.0
      - 1.0
      - 0.6
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 7.3
      - 5.1
      - 0.6
      - 1.6
      - 1.0
      - 0.6
      - 1.3
      - 0.3
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 0.6
      - 0.3
      - 1.0
      - 4.8
      - 1.9
      - 1.6
      - 1.0
      - 1.0
      - 0.6
      - 1.0
      - 5.8
      - 0.6
      - 1.0
      - 16.3
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 7.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 0.6
      - 1.0
      - 1.0
      - 0.3
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 0.6
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
