!!submodule.data.MainConfig
charts:
  Bacteria_Genus:
    data:
      Bacteria:
      - 6
      - 3
      - 19
      - 2
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count Bacteria
      xAxisTitle: null
      xCategories:
      - Salmonella
      - Escherichia
      - Pseudomonas
      - Caulobacter
      yAxisTitle: null
      yCategories:
      - 20.0
      - 10.0
      - 63.3
      - 6.7
  Projects:
    data:
      project:
      - 21
      - 5
      - 201
      - 8
    settings:
      subtitle: null
      tabTitle: Projects
      title: Project Counts with Measured Samples
      xAxisTitle: null
      xCategories:
      - Q_MS_RUN
      - Q_MICROARRAY_RUN
      - Q_NGS_SINGLE_SAMPLE_RUN
      - Multi_omics
      yAxisTitle: null
      yCategories:
      - 8.9
      - 2.1
      - 85.5
      - 3.4
  Available_Workflows_MA_RNA:
    data:
      stargazers_count:
      - 1.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows MA_RNA
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/qbic-wf-microarrayQC
      yAxisTitle: null
      yCategories:
      - Microarray QC workflow mainly using the R package oligo
  Project_Multi_omics:
    data:
      multiomics:
      - 7
      - 1
    settings:
      subtitle: null
      tabTitle: Projects
      title: Multiomics count
      xAxisTitle: null
      xCategories:
      - Mass Spectrometry + NGS
      - Mass Spectrometry + Microarray
      yAxisTitle: null
      yCategories: null
  SuperKingdom:
    data:
      SuperKingdom:
      - 22
      - 1321
      - 30
      - 3399
      - 88
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count by Domain
      xAxisTitle: null
      xCategories:
      - unclassified sequences
      - Other Eukaryota
      - Bacteria
      - Homo sapiens
      - Other
      yAxisTitle: null
      yCategories:
      - 0.5
      - 27.2
      - 0.6
      - 69.9
      - 1.8
  Species_Genus:
    data:
      Species_Genus:
      - Apis
      - Mus
      - Cavia
      - Rosa
      - Escherichia
      - Rattus
      - Asparagus
      - Arabidopsis
      - Corylus
      - Corylus
      - Pseudomonas
      - Lolium
      - null
      - Capra
      - Solanum
      - Corylus
      - Solanum
      - Homo
      - Bos
      - Caulobacter
      - Galleria
      - Caenorhabditis
      - Salmonella
      - Pseudomonas
      - Nicotiana
      - Saccharomyces
      - null
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - ' Apis mellifera mellifera'
      - Mus musculus
      - Cavia aperea
      - Rosa wichurana
      - Escherichia coli
      - Rattus norvegicus
      - Asparagus officinalis
      - Arabidopsis thaliana
      - Corylus maxima
      - Corylus avellana
      - Pseudomonas aeruginosa
      - Lolium perenne
      - Unidentified
      - Capra hircus
      - Solanum tuberosum
      - Corylus spp.
      - Solanum lycopersicum
      - Homo sapiens
      - Bos taurus
      - Caulobacter crescentus CB15
      - Galleria mellonella
      - Caenorhabditis elegans
      - Salmonella enterica subsp. enterica serovar Typhimurium str. SL1344
      - Pseudomonas aeruginosa strain PAO1
      - Nicothiana benthamiana
      - Saccharomyces cerevisiae
      - Other
      yAxisTitle: null
      yCategories: null
  Available_Workflows_NGS_RNA:
    data:
      stargazers_count:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows NGS_RNA
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/rnamapping
      - https://api.github.com/repos/qbicsoftware/rnacount
      - https://api.github.com/repos/qbicsoftware/rnaseq
      - https://api.github.com/repos/qbicsoftware/ngsqc
      - https://api.github.com/repos/qbicsoftware/optitype-workflow
      - https://api.github.com/repos/qbicsoftware/epaa-workflow
      yAxisTitle: null
      yCategories:
      - ''
      - Quality Control on fastq files
      - ''
      - RNAseq workflow
      - ''
      - ''
  Available_Workflows_NGS_DNA:
    data:
      stargazers_count:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows NGS_DNA
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/variantcalling
      - https://api.github.com/repos/qbicsoftware/mapping
      - https://api.github.com/repos/qbicsoftware/exomseq
      - https://api.github.com/repos/qbicsoftware/ngsqc
      - https://api.github.com/repos/qbicsoftware/16Smetagenomics-taxonomic-profiling
      - https://api.github.com/repos/qbicsoftware/optitype-workflow
      - https://api.github.com/repos/qbicsoftware/epaa-workflow
      yAxisTitle: null
      yCategories:
      - ''
      - Quality Control on fastq files
      - ''
      - ''
      - Repository for variant calling pipeline using FreeBayes
      - ''
      - ''
  Eukaryota_Genus:
    data:
      Eukaryota:
      - 34
      - 16
      - 237
      - 153
      - 14
      - 1
      - 13
      - 587
      - 2
      - 1
      - 12
      - 15
      - 1
      - 200
      - 3
      - 32
    settings:
      subtitle: null
      tabTitle: Organisms
      title: Sample Count Eukaryota
      xAxisTitle: null
      xCategories:
      - Nicotiana
      - Galleria
      - Arabidopsis
      - Apis
      - Bos
      - Lolium
      - Asparagus
      - Mus
      - Saccharomyces
      - Rosa
      - Cavia
      - Rattus
      - Caenorhabditis
      - Solanum
      - Capra
      - Corylus
      yAxisTitle: null
      yCategories:
      - 2.6
      - 1.2
      - 17.9
      - 11.6
      - 1.1
      - 0.1
      - 1.0
      - 44.4
      - 0.2
      - 0.1
      - 0.9
      - 1.1
      - 0.1
      - 15.1
      - 0.2
      - 2.4
  Available_Workflows_MS_PX:
    data:
      stargazers_count:
      - 6.0
      - 2.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows MS_PX
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/mqrun
      - https://api.github.com/repos/qbicsoftware/qcprot
      yAxisTitle: null
      yCategories:
      - Automate MaxQuant
      - Quality control for mass spec proteomics
  Available_Workflows_OTHER:
    data:
      stargazers_count:
      - 1.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows OTHER
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/qbic-workflow-nf-rnaseq
      yAxisTitle: null
      yCategories:
      - Our RNAseq workflow modularized in nextflow
  Workflow_Execution_Counts:
    data:
      Counts:
      - 11
      - 222
      - 747
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Workflow Execution Counts
      xAxisTitle: null
      xCategories:
      - MA
      - MS
      - NGS
      yAxisTitle: null
      yCategories:
      - 1.1
      - 22.7
      - 76.2
  Sample_Types:
    data:
      Samples:
      - PEPTIDES: 51
        SMALLMOLECULES: 127
        PHOSPHOPROTEINS: 30
        PROTEINS: 277
      - RNA: 40
        DNA: 94
      - RNA: 346
        DNA: 890
    settings:
      subtitle: null
      tabTitle: Samples
      title: Number of Already Measured Samples
      xAxisTitle: null
      xCategories:
      - Q_MS_RUN
      - Q_MICROARRAY_RUN
      - Q_NGS_SINGLE_SAMPLE_RUN
      yAxisTitle: null
      yCategories: null
  Bacteria_Species:
    data:
      Bacteria:
      - 6
      - 3
      - 8
      - 11
      - 2
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - Salmonella enterica subsp. enterica serovar Typhimurium str. SL1344
      - Escherichia coli
      - Pseudomonas aeruginosa strain PAO1
      - Pseudomonas aeruginosa
      - Caulobacter crescentus CB15
      yAxisTitle: null
      yCategories:
      - 20.0
      - 10.0
      - 26.7
      - 36.7
      - 6.7
  Available_Workflows_MS_LX:
    data:
      stargazers_count:
      - 0.0
      - 0.0
    settings:
      subtitle: null
      tabTitle: Workflow
      title: Available Workflows MS_LX
      xAxisTitle: null
      xCategories:
      - https://api.github.com/repos/qbicsoftware/ligandomics-ID-workflow-copro
      - https://api.github.com/repos/qbicsoftware/ligandomics-ID-workflow
      yAxisTitle: null
      yCategories:
      - ''
      - ''
  Eukaryota_Species:
    data:
      Eukaryota:
      - 153
      - 3
      - 587
      - 12
      - 1
      - 10
      - 15
      - 190
      - 15
      - 14
      - 16
      - 13
      - 237
      - 1
      - 2
      - 15
      - 1
      - 34
      - 2
    settings:
      subtitle: null
      tabTitle: Organisms
      title: ''
      xAxisTitle: null
      xCategories:
      - ' Apis mellifera mellifera'
      - Capra hircus
      - Mus musculus
      - Cavia aperea
      - Rosa wichurana
      - Solanum tuberosum
      - Corylus spp.
      - Solanum lycopersicum
      - Rattus norvegicus
      - Bos taurus
      - Galleria mellonella
      - Asparagus officinalis
      - Arabidopsis thaliana
      - Caenorhabditis elegans
      - Corylus maxima
      - Corylus avellana
      - Lolium perenne
      - Nicothiana benthamiana
      - Saccharomyces cerevisiae
      yAxisTitle: null
      yCategories:
      - 11.6
      - 0.2
      - 44.4
      - 0.9
      - 0.1
      - 0.8
      - 1.1
      - 14.4
      - 1.1
      - 1.1
      - 1.2
      - 1.0
      - 17.9
      - 0.1
      - 0.2
      - 1.1
      - 0.1
      - 2.6
      - 0.2
